app:
  jdbc-template:
    fetch-size: ${FETCH_SIZE:20000}

spring:
  data:
    rest:
      basePath: /api/opc/v1
  datasource:
    url: ${DBURL:jdbc:oracle:thin:@SID}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ${DBUSER}
    password: ${DBPASS}
  liquibase:
    enabled: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
